const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Tilemap,
		C3.Behaviors.MoveTo,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Mosaico: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{MoverPara: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{balaoFalaTodoMundo: 0},
	{Áudio: 0},
	{Sprite32: 0},
	{Mouse: 0},
	{balaoFrost: 0},
	{balaoFrost2: 0},
	{balaoAlberto: 0},
	{txtAlberto: 0},
	{txtValkinho: 0},
	{balaoValkinho: 0},
	{txtHB: 0},
	{balaoHB: 0},
	{balaoMaVi: 0},
	{txtMaVi: 0},
	{txtRaissa: 0},
	{balaoRaissa: 0},
	{caixaMenu: 0},
	{Piscar: 0},
	{txtMenu1: 0},
	{seta2: 0},
	{Teclado: 0},
	{txtMenu3: 0},
	{txtMenu2: 0},
	{txtHenri: 0},
	{balaoHenri: 0},
	{txtAlberto2: 0},
	{balaoAlberto2: 0},
	{txtMax: 0},
	{balaoYago: 0},
	{txtAlberto4: 0},
	{balaoMax: 0},
	{txtyAGO: 0},
	{balaoAlberto4: 0},
	{balaoEverthon: 0},
	{txtEverthon: 0},
	{txtDG: 0},
	{balaoDG: 0},
	{txtHenri2: 0},
	{balaoHenri2: 0},
	{txtThalita: 0},
	{balaoThalita: 0},
	{txtLuna: 0},
	{balaoLuna: 0},
	{txtAna: 0},
	{balaoAna: 0},
	{txtMaVi2: 0},
	{balaoMaVi2: 0},
	{txtLucas: 0},
	{balaoLucas: 0},
	{txtVitoria: 0},
	{balaoVitoria: 0},
	{txtRaissa2: 0},
	{balaoRaissa2: 0},
	{Sprite31: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{mesaLab1: 0},
	{Sprite38: 0},
	{mesaLab3: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{Sprite43: 0},
	{txtValkinho2: 0},
	{balaoValkinho2: 0},
	{balaoHenriqueLab3: 0},
	{txtAlbertoLab: 0},
	{txtMaviLab: 0},
	{txtVitoriaLab: 0},
	{txtLucasLab: 0},
	{txtHenriqueLab: 0},
	{txtJoaoGabrielLab: 0},
	{txtValkinhoLab: 0},
	{txtLunaLab: 0},
	{txtEverthonLab: 0},
	{txtRaissaLab: 0},
	{txtGabrielLab: 0},
	{txtAnaLab: 0},
	{txtDavidLab: 0},
	{Sprite44: 0},
	{mesaLab2: 0},
	{txtMaxLab: 0},
	{txtYagoLab: 0},
	{txtThalitaLab: 0},
	{optVitoria: 0},
	{optAna: 0},
	{optAlberto: 0},
	{optJoaoGabriel: 0},
	{optLucas: 0},
	{optMax: 0},
	{optMariaVitoria: 0},
	{optDavid: 0},
	{optThalita: 0},
	{optLuna: 0},
	{optJoaoPedro: 0},
	{optEverthon: 0},
	{optYago: 0},
	{optGabriel: 0},
	{optRaissa: 0},
	{optHenrique: 0},
	{optValkinho: 0},
	{balaoVitoriaLab: 0},
	{balaoAnaLab: 0},
	{balaoAlbertoLab: 0},
	{balaoJoaoGabrielLab: 0},
	{balaoLucasLab: 0},
	{balaoMaxLab: 0},
	{balaoMaViLab: 0},
	{balaoDavidLab: 0},
	{balaoThalitaLab: 0},
	{balaoLunaLab: 0},
	{balaoEverthonLab: 0},
	{balaoYagoLab: 0},
	{balaoGabrielLab: 0},
	{balaoJoaoPedroLab: 0},
	{txtJoaoPedroLab: 0},
	{balaoRaissaLab: 0},
	{balaoHenriqueLab: 0},
	{balaoValkinhoLab: 0},
	{txtMenu4: 0},
	{seta: 0},
	{Toque: 0},
	{Sprite37: 0},
	{Sprite39: 0},
	{Sprite45: 0},
	{Sprite46: 0},
	{Sprite47: 0},
	{Sprite48: 0},
	{Sprite49: 0},
	{Sprite50: 0},
	{Sprite51: 0},
	{btnPlay: 0},
	{btnEncerrarAula: 0},
	{balaoHBLab: 0},
	{txtHBLab: 0},
	{Texto: 0},
	{txtHBFinal: 0},
	{balaoHBFinal: 0},
	{f1: 0},
	{Projétil: 0},
	{fotoAlberto: 0},
	{fotoYago: 0},
	{fotoGabriel: 0},
	{fotoLuna: 0},
	{fotoMaVI: 0},
	{fotoHenri: 0},
	{fotoMax: 0},
	{fotoJoaoGabriel: 0},
	{fotoLucas: 0},
	{fotoThalita: 0},
	{fotoFrost: 0},
	{fotoAna: 0},
	{fotoDG: 0},
	{fotoEverthon: 0},
	{fotoVitoria: 0},
	{fotoRaissa: 0},
	{Sprite52: 0},
	{Sprite53: 0},
	{Sprite54: 0},
	{fotoMariaVitoria: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{fotoValkinho: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{btnReiniciar: 0},
	{balaoFrostFala: 0},
	{txtFrostFala: 0},
	{txtGabriel: 0},
	{balaoGabriel: 0},
	{txtJoaoGabriel: 0},
	{balaoJoaoGabriel: 0},
	{txtHenri3: 0},
	{txtHenri4: 0},
	{balaoRaissa3: 0},
	{Sprite59: 0},
	{escolhaAula: 0},
	{tempoEncerrar: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	balaoFalaTodoMundo: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	balaoFrost: class extends self.ISpriteInstance {},
	balaoFrost2: class extends self.ISpriteInstance {},
	balaoAlberto: class extends self.ISpriteInstance {},
	txtAlberto: class extends self.ITextInstance {},
	txtValkinho: class extends self.ITextInstance {},
	balaoValkinho: class extends self.ISpriteInstance {},
	txtHB: class extends self.ITextInstance {},
	balaoHB: class extends self.ISpriteInstance {},
	balaoMaVi: class extends self.ISpriteInstance {},
	txtMaVi: class extends self.ITextInstance {},
	txtRaissa: class extends self.ITextInstance {},
	balaoRaissa: class extends self.ISpriteInstance {},
	caixaMenu: class extends self.ISpriteInstance {},
	txtMenu1: class extends self.ITextInstance {},
	seta2: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	txtMenu3: class extends self.ITextInstance {},
	txtMenu2: class extends self.ITextInstance {},
	txtHenri: class extends self.ITextInstance {},
	balaoHenri: class extends self.ISpriteInstance {},
	txtAlberto2: class extends self.ITextInstance {},
	balaoAlberto2: class extends self.ISpriteInstance {},
	txtMax: class extends self.ITextInstance {},
	balaoYago: class extends self.ISpriteInstance {},
	txtAlberto4: class extends self.ITextInstance {},
	balaoMax: class extends self.ISpriteInstance {},
	txtyAGO: class extends self.ITextInstance {},
	balaoAlberto4: class extends self.ISpriteInstance {},
	balaoEverthon: class extends self.ISpriteInstance {},
	txtEverthon: class extends self.ITextInstance {},
	txtDG: class extends self.ITextInstance {},
	balaoDG: class extends self.ISpriteInstance {},
	txtHenri2: class extends self.ITextInstance {},
	balaoHenri2: class extends self.ISpriteInstance {},
	txtThalita: class extends self.ITextInstance {},
	balaoThalita: class extends self.ISpriteInstance {},
	txtLuna: class extends self.ITextInstance {},
	balaoLuna: class extends self.ISpriteInstance {},
	txtAna: class extends self.ITextInstance {},
	balaoAna: class extends self.ISpriteInstance {},
	txtMaVi2: class extends self.ITextInstance {},
	balaoMaVi2: class extends self.ISpriteInstance {},
	txtLucas: class extends self.ITextInstance {},
	balaoLucas: class extends self.ISpriteInstance {},
	txtVitoria: class extends self.ITextInstance {},
	balaoVitoria: class extends self.ISpriteInstance {},
	txtRaissa2: class extends self.ITextInstance {},
	balaoRaissa2: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	mesaLab1: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	mesaLab3: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	txtValkinho2: class extends self.ITextInstance {},
	balaoValkinho2: class extends self.ISpriteInstance {},
	balaoHenriqueLab3: class extends self.ISpriteInstance {},
	txtAlbertoLab: class extends self.ITextInstance {},
	txtMaviLab: class extends self.ITextInstance {},
	txtVitoriaLab: class extends self.ITextInstance {},
	txtLucasLab: class extends self.ITextInstance {},
	txtHenriqueLab: class extends self.ITextInstance {},
	txtJoaoGabrielLab: class extends self.ITextInstance {},
	txtValkinhoLab: class extends self.ITextInstance {},
	txtLunaLab: class extends self.ITextInstance {},
	txtEverthonLab: class extends self.ITextInstance {},
	txtRaissaLab: class extends self.ITextInstance {},
	txtGabrielLab: class extends self.ITextInstance {},
	txtAnaLab: class extends self.ITextInstance {},
	txtDavidLab: class extends self.ITextInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	mesaLab2: class extends self.ISpriteInstance {},
	txtMaxLab: class extends self.ITextInstance {},
	txtYagoLab: class extends self.ITextInstance {},
	txtThalitaLab: class extends self.ITextInstance {},
	optVitoria: class extends self.ITextInstance {},
	optAna: class extends self.ITextInstance {},
	optAlberto: class extends self.ITextInstance {},
	optJoaoGabriel: class extends self.ITextInstance {},
	optLucas: class extends self.ITextInstance {},
	optMax: class extends self.ITextInstance {},
	optMariaVitoria: class extends self.ITextInstance {},
	optDavid: class extends self.ITextInstance {},
	optThalita: class extends self.ITextInstance {},
	optLuna: class extends self.ITextInstance {},
	optJoaoPedro: class extends self.ITextInstance {},
	optEverthon: class extends self.ITextInstance {},
	optYago: class extends self.ITextInstance {},
	optGabriel: class extends self.ITextInstance {},
	optRaissa: class extends self.ITextInstance {},
	optHenrique: class extends self.ITextInstance {},
	optValkinho: class extends self.ITextInstance {},
	balaoVitoriaLab: class extends self.ISpriteInstance {},
	balaoAnaLab: class extends self.ISpriteInstance {},
	balaoAlbertoLab: class extends self.ISpriteInstance {},
	balaoJoaoGabrielLab: class extends self.ISpriteInstance {},
	balaoLucasLab: class extends self.ISpriteInstance {},
	balaoMaxLab: class extends self.ISpriteInstance {},
	balaoMaViLab: class extends self.ISpriteInstance {},
	balaoDavidLab: class extends self.ISpriteInstance {},
	balaoThalitaLab: class extends self.ISpriteInstance {},
	balaoLunaLab: class extends self.ISpriteInstance {},
	balaoEverthonLab: class extends self.ISpriteInstance {},
	balaoYagoLab: class extends self.ISpriteInstance {},
	balaoGabrielLab: class extends self.ISpriteInstance {},
	balaoJoaoPedroLab: class extends self.ISpriteInstance {},
	txtJoaoPedroLab: class extends self.ITextInstance {},
	balaoRaissaLab: class extends self.ISpriteInstance {},
	balaoHenriqueLab: class extends self.ISpriteInstance {},
	balaoValkinhoLab: class extends self.ISpriteInstance {},
	txtMenu4: class extends self.ITextInstance {},
	seta: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	btnEncerrarAula: class extends self.ISpriteInstance {},
	balaoHBLab: class extends self.ISpriteInstance {},
	txtHBLab: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	txtHBFinal: class extends self.ITextInstance {},
	balaoHBFinal: class extends self.ISpriteInstance {},
	f1: class extends self.ISpriteInstance {},
	fotoAlberto: class extends self.ISpriteInstance {},
	fotoYago: class extends self.ISpriteInstance {},
	fotoGabriel: class extends self.ISpriteInstance {},
	fotoLuna: class extends self.ISpriteInstance {},
	fotoMaVI: class extends self.ISpriteInstance {},
	fotoHenri: class extends self.ISpriteInstance {},
	fotoMax: class extends self.ISpriteInstance {},
	fotoJoaoGabriel: class extends self.ISpriteInstance {},
	fotoLucas: class extends self.ISpriteInstance {},
	fotoThalita: class extends self.ISpriteInstance {},
	fotoFrost: class extends self.ISpriteInstance {},
	fotoAna: class extends self.ISpriteInstance {},
	fotoDG: class extends self.ISpriteInstance {},
	fotoEverthon: class extends self.ISpriteInstance {},
	fotoVitoria: class extends self.ISpriteInstance {},
	fotoRaissa: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	fotoMariaVitoria: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	fotoValkinho: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	btnReiniciar: class extends self.ISpriteInstance {},
	balaoFrostFala: class extends self.ISpriteInstance {},
	txtFrostFala: class extends self.ITextInstance {},
	txtGabriel: class extends self.ITextInstance {},
	balaoGabriel: class extends self.ISpriteInstance {},
	txtJoaoGabriel: class extends self.ITextInstance {},
	balaoJoaoGabriel: class extends self.ISpriteInstance {},
	txtHenri3: class extends self.ITextInstance {},
	txtHenri4: class extends self.ITextInstance {},
	balaoRaissa3: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {}
}